//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PF2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerOption
    {
        public AnswerOption()
        {
            this.QuizAnswerQuestion = new HashSet<QuizAnswerQuestion>();
        }
    
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public string Answer { get; set; }
        public bool IsCorrect { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual ICollection<QuizAnswerQuestion> QuizAnswerQuestion { get; set; }
    }
}
