//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PF2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Answer = new HashSet<AnswerOption>();
            this.QuizAnswerQuestion = new HashSet<QuizAnswerQuestion>();
        }
    
        public int Id { get; set; }
        public int NodeId { get; set; }
        public string Enunciation { get; set; }
    
        public virtual Node Node { get; set; }
        public virtual ICollection<AnswerOption> Answer { get; set; }
        public virtual ICollection<QuizAnswerQuestion> QuizAnswerQuestion { get; set; }
    }
}
