//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PF2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizAnswerQuestion
    {
        public int QuizId { get; set; }
        public Nullable<int> AnswerOptionId { get; set; }
        public int QuestionId { get; set; }
    
        public virtual Quiz Quiz { get; set; }
        public virtual AnswerOption AnswerOption { get; set; }
        public virtual Question Question { get; set; }
    }
}
