//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PF2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        public Quiz()
        {
            this.QuizAnswerQuestion = new HashSet<QuizAnswerQuestion>();
        }
    
        public int Id { get; set; }
        public string AspNetUsersId { get; set; }
        public int NodeId { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int NumQuestions { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Node Node { get; set; }
        public virtual ICollection<QuizAnswerQuestion> QuizAnswerQuestion { get; set; }
    }
}
